---
- name: Add test block to /etc/profile
  lineinfile:
    dest: /etc/profile
    line: '#This is a test block added by Ansible......{{ ansible_user_id }}'
    insertafter: EOF

- name: Set TMOUT variable in /etc/profile
  lineinfile:
    dest: /etc/profile
    line: 'export TMOUT=1800'
    insertafter: '#This is a test block added by Ansible......{{ ansible_user_id }}'

# tasks file for system_profile
