---
- name: Install Apache web server
  become: true
  package:
    name: "{{ apache_service_name }}"
    state: present

- name: Create index.html files
  template:
    src: index.html.j2
    dest: "/tmp/{{ inventory_hostname }}.html"

- name: Copy index.html files to web servers
  copy:
    src: "/tmp/{{ inventory_hostname }}.html"
    dest: "{{ apache_document_root }}/index.html"
    remote_src: yes
  notify:
    - Restart Apache

- name: Set permissions on index.html files
  file:
    path: "{{ apache_document_root }}/index.html"
    mode: "0444"

- name: Ensure Apache service is running
  service:
    name: "{{ apache_service_name }}"
    state: started
    enabled: true

# tasks file for webserver

